# definizione del compilatore e dei falg di compilazione che vengono usate dalle regole implicite
CC=gcc
CFLAGS=-std=c11 -Wall -O -g
LDLIBS=-lm

# elenco degli eseguibili da creare
all:  primi primi2 sommad



